config/routes.rb
Grapefruit::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  match "become" => 'admin#become', via: [:get, :post]

  devise_scope :user do
    authenticated :user do
      root 'home#dashboard', as: "authenticated_root"
    end
    unauthenticated :user do
      root 'guest#index'
    end
  end

  get 'about' => 'guest#about'
  get 'tos' => 'guest#tos'
  get 'contact' => 'guest#contact'
  get 'contribute' => 'guest#contribute'
  get 'privacy' => 'guest#privacy'

  devise_for :users, skip: [:sessions, :passwords, :registrations]

  as :user do

    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session

    get 'forgot' => 'devise/passwords#new', as: :new_user_password
    post 'forgot' => 'devise/passwords#create'
    put 'forgot' => 'devise/passwords#update', as: :user_password
    get 'forgot/change' => 'devise/passwords#edit', as: :edit_user_password

    get   'join' => 'devise/registrations#new',    as: :new_user_registration
    post  'join' => 'custom_registration#create', as: :user_registration
    get 'cancel'   => 'devise/registrations#cancel', as: :cancel_user_registration
    get 'settings' => 'devise/registrations#edit',   as: :edit_user_registration
    put 'join' => 'devise/registrations#update', as: :update_user_registration

    post 'management_state' => 'home#management_state'

  end

  resources :courses do

    get 'iframe'
    get 'students'
    get 'manage'
    get 'stats'

    get 'gradelist' => 'grades#gradelist'

    resources :assignments do
      resources :submissions
      resources :grades
    end

    resources :assignment_types, only: [:index, :create, :destroy, :update]

    resources :documents, shallow: true

    resources :course_users, only: [:create, :destroy]

    resources :capsules do

      resources :documents, shallow: true

      resources :lectures do
        get :toggle_live
        get :comments
        post :submit_comment
        get :list_comments
        resources :documents, shallow: true
        resources :videos, except: :index do
          resources :video_texts, only: [:new, :create, :index, :update, :destroy]
        end
      end

      resources :problem_sets

    end

    resources :topics, only: [:new, :create, :show, :index, :destroy] do
      resources :replies, only: [:create]
    end

    resources :announcements, except: [:show]

    get 'new_to_class' => 'announcements#new_to_class'
    post 'send_to_class' => 'announcements#send_to_class'

  end

end

app/models/capsule.rb
# == Schema Information
#
# Table name: capsules
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  course_id   :integer
#  description :text(65535)
#

class Capsule < ActiveRecord::Base

  # Validations
  # ========================================================
  validates :name, presence: true

  # Relationships
  # ========================================================
  belongs_to :course
  has_many :lectures, dependent: :destroy
  has_many :problem_sets, dependent: :destroy
  has_many :documents, dependent: :destroy

end

app/controllers/capsules_controller.rb
class CapsulesController < ApplicationController

  before_filter :get_course
  before_filter :get_capsule, only: [:show, :edit, :update, :destroy]
  before_filter :get_all_course_capsules, only: [:new, :show]
  before_filter :authenticate_user!

  layout "course"

  def new
    @capsule = @course.capsules.new
    @capsule.name = "New Capsule"
    authorize! :create, @capsule
  end

  def create
    @capsule = @course.capsules.new(capsule_params)
    authorize! :create, @capsule
    if @capsule.save
      flash[:success] = "Capsule created!"
      redirect_to course_manage_path(@course)
    else
      render 'new'
    end
  end

  def show
    @lectures = @capsule.lectures.order("created_at ASC")
    @problem_sets = @capsule.problem_sets.order("created_at ASC")
    @documents = @capsule.documents
    @lectures.build
    @problem_sets.build
  end

  def edit
    authorize! :update, @capsule
  end

  def update
    authorize! :update, @capsule
    if @capsule.update_attributes(capsule_params)
      flash[:success] = "Capsule updated!"
      redirect_to course_manage_path(@course)
    else
      render "edit"
    end
  end

  def destroy
    authorize! :delete, @capsule
    @capsule.destroy
    redirect_to :back
  end

private

  def capsule_params
    params.require(:capsule).permit(:name, :description)
  end

end

app/helpers/capsules_helper.rb
module CapsulesHelper
end

app/views/capsules/_capsule.html.erb
<% if capsule.id %>

	<li>
		<% if @capsule == capsule && @lecture.blank? %>
			<span><%= capsule.name %> &rsaquo; </span>
		<% else %>
			<%= link_to capsule.name, course_capsule_path(capsule.course, capsule),
				class: (@capsule == capsule) ? 'active' : '' %>
		<% end %>
	</li>

	<% if @capsule == capsule %>

		<% if @capsule.lectures.empty? %>

			<ul><li class="grey">No lectures found!</li>
			</ul>
		<% else %>

			<ul>
				<%= render @capsule.lectures %>
			</ul>

		<% end %>

	<% end %>

<% end %>

app/views/capsules/_manage_capsules.html.erb
<div class="capsule-container">

  <h4>
    Capsule:
    <%= link_to capsule.name, "#", class: "slide-reveal", data: { reveal: 'capsule-' + capsule.id.to_s } %>
  </h4>

  <div class="capsule reveal-hidden" id="capsule-<%= capsule.id %>">

    <p>

      <%= link_to "edit capsule info", edit_course_capsule_path(@course, capsule), class: "add" %>

      <span class="space"></span>

      <%= link_to "show files", "#",
          class: "add secondary slide-reveal",
          data: {
            reveal: 'capsule-' + capsule.id.to_s + '-files',
            initial: "manage files #{parens(capsule.documents.count)}",
            active: 'done with files'
          } %>
      <%= link_to "view as student &#10148;".html_safe,
      course_capsule_path(@course, capsule), class: "add secondary" %>

      <span class="space"></span>

      <%= link_to "add lecture", new_course_capsule_lecture_path(@course, capsule), class: "add" %>

    </p>

    <div id="capsule-<%= capsule.id %>-files" class="reveal-hidden panel">

      <% if capsule.documents.empty? %>
        <p>No capsule files yet!</p>
      <% else %>
        <h6>Capsule Files (examples: chapter summary, reference sheets, etc)</h6>
      <% end %>

      <%= render "documents/documents", container: capsule, documents: capsule.documents %>

      <h5><%= link_to "add file", new_course_capsule_document_path(@course, capsule), class: "" %></h5>

    </div>

    <% if capsule.lectures.empty? %>
      <p class="grey">There aren't any lectures in this capsule yet.</p>
    <% end %>

    <%= render collection: capsule.lectures, partial: "lectures/manage_lecture", as: :lecture %>


  </div>

</div>

app/views/capsules/edit.html.erb
<% page_title "Editing #{@capsule.name}" %>

<%= breadcrumbs([
      link_to('All Courses', courses_path),
      link_to(@course.name, course_path(@course)),
      link_to("Edit #{@capsule.name} from #{@course.name}", void, class: "current")
    ]) %>

<div class="landing">

  <div class="description">
    <h2>Edit <%= @capsule.name %> from <%= @course.name %></h2>
  </div>

  <div class="login">
    <%= form_for [@course, @capsule] do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.text_field :name, placeholder: "Capsule Name", autofocus: true %>

      <%= f.text_area :description, style: "height: 20em", placeholder: "This topic consists of ..." %>

      <div>

        <%= f.submit "Update Capsule", class: "button small" %>

        <%= link_to "Delete Capsule",
                    course_capsule_path(@course, @capsule),
                    data: { confirm: "Are you want to delete this capsule? This action cannot be undone." },
                    method: :delete,
                    class: "button alert small" %>

      </div>

    <% end %>
  </div>

</div>

app/views/capsules/new.html.erb
<% page_title "Creating New Capsule" %>

<div class="landing">

  <div class="description">
    <h2>Add Capsule to <%= @course.name %></h2>
  </div>

  <div class="login">
    
    <%= form_for [@course, @capsule] do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.text_field :name, placeholder: "Capsule Name", autofocus: true %>

      <%= f.text_area :description, placeholder: "This topic consists of ..." %>

      <div><%= f.submit "Add Capsule", class: "button small" %></div>  
    <% end %>
    
  </div>

</div>

app/views/capsules/show.html.erb
<% page_title (@capsule.name + ' :: ' + @course.name) %>

<h3><%= @capsule.name %></h3>

<% unless @capsule.description.blank? %>
  <p class="description"><%= @capsule.description %></p>
<% end %>

<%= link_to_textbook_problem_sets(@course) %>

<% if @problem_sets.present? %>
  <table class="listing">
    <thead>
      <th>
        Problem Sets
      </th>
    </thead>
    <%= render collection: @problem_sets, partial: "problem_sets/table_problem_set", as: :problem_set %>
  </table>
<% end %>

<%= render "documents/documents", container: @capsule %>

<% if @documents.empty? && @problem_sets.empty? && @capsule.description.blank? %>
  <p class="grey">Looks like there's no content in this capsule yet!</p>
  <p class="grey">Try clicking on a lecture instead.</p>
<% end %>